-- 코드를 작성해주세요

select count(*) as FISH_COUNT, FISH_NAME from FISH_NAME_INFO
join FISH_INFO
on FISH_NAME_INFO.FISH_TYPE = FISH_INFO.FISH_TYPE
group by FISH_NAME_INFO.FISH_TYPE, FISH_NAME_INFO.FISH_NAME
order by FISH_COUNT DESC;